#!/usr/bin/env bash
# test/mirror-regression.sh — Regression: Claude-to-Copilot mirror behavior.
#   Verifies that bootstrap produces identical content for Claude and Copilot
#   consumers from a single generated CLAUDE.md source, and that bootstrap
#   is idempotent (running twice produces the same output).
# Usage: bash test/mirror-regression.sh
set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo "$(dirname "$0")/..")"

PASS=0
FAIL=0
FAILURES=()

_ok() {
    PASS=$((PASS + 1))
    printf "  \033[32m✓\033[0m %s\n" "$1"
}

_fail() {
    FAIL=$((FAIL + 1))
    FAILURES+=("$1: $2")
    printf "  \033[31m✗\033[0m %s — %s\n" "$1" "$2"
}

# On Windows/MSYS without Developer Mode, `ln -sf` cannot create real symlinks
# (it silently copies or fails), so the `-L` symlink assertions below are
# meaningless there. Skip the symlink-dependent checks but keep the
# content-generation and idempotency checks, which don't depend on symlinks.
_is_windows() {
    case "$(uname -s)" in
        MINGW*|MSYS*|CYGWIN*) return 0 ;;
        *) return 1 ;;
    esac
}

echo
echo "Claude-to-Copilot mirror regression"
echo "════════════════════════════════════════════════"

if _is_windows; then
    echo "  (Windows detected — skipping symlink assertions; ln -sf cannot create real symlinks without Developer Mode)"
fi

# ── Setup: run bootstrap in a temp HOME ─────────────────────────────────────
FAKE_HOME="$(mktemp -d 2>/dev/null || mktemp -d -t mirror)"
trap 'rm -rf "$FAKE_HOME"' EXIT

REPO_ROOT="$(pwd)"

# Create the minimal dotfiles tree bootstrap expects
FAKE_DOTFILES="$FAKE_HOME/dotfiles"
mkdir -p "$FAKE_DOTFILES/bin"
mkdir -p "$FAKE_DOTFILES/instructions/_local"
mkdir -p "$FAKE_DOTFILES/skills/_local"
mkdir -p "$FAKE_DOTFILES/secrets"
mkdir -p "$FAKE_DOTFILES/working"
mkdir -p "$FAKE_HOME/.claude"
mkdir -p "$FAKE_HOME/.copilot"

# Copy required source files
cp "$REPO_ROOT/CLAUDE.base.md" "$FAKE_DOTFILES/CLAUDE.base.md"
cp "$REPO_ROOT/bin/bootstrap.sh" "$FAKE_DOTFILES/bin/bootstrap.sh"

# Copy example env files if they exist (bootstrap checks for them)
[[ -f "$REPO_ROOT/.env.agent.example" ]] && cp "$REPO_ROOT/.env.agent.example" "$FAKE_DOTFILES/.env.agent.example"
[[ -f "$REPO_ROOT/.env.secrets.example" ]] && cp "$REPO_ROOT/.env.secrets.example" "$FAKE_DOTFILES/.env.secrets.example"

# Create a sample local instruction to exercise that path
cat > "$FAKE_DOTFILES/instructions/_local/sample.instructions.md" << 'EOF'
# Sample instruction for test
This is a test instruction that should be auto-loaded.
EOF

# Run bootstrap with HOME overridden (skip steps that need git/network)
# We only need steps 1-2 and the copilot deploy (step at line ~384)
# Extract just the CLAUDE.md generation + copilot mirror logic
cat > "$FAKE_HOME/run-mirror.sh" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
export HOME="$1"
DOTFILES="$HOME/dotfiles"
CLAUDE_DIR="$HOME/.claude"
COPILOT_DIR="$HOME/.copilot"

mkdir -p "$CLAUDE_DIR" "$COPILOT_DIR"
mkdir -p "$DOTFILES/skills/_local"
mkdir -p "$DOTFILES/instructions/_local"

# Generate CLAUDE.md (mirrors bootstrap.sh step 2)
{
    printf '<!-- GENERATED FILE — do not edit directly.\n'
    printf '     Built by bootstrap.sh from CLAUDE.base.md + local instruction refs.\n'
    printf '     Edit CLAUDE.base.md instead, then run: bash ~/dotfiles/bin/bootstrap.sh -->\n'
    awk 'BEGIN{skip=1} /-->/{skip=0; next} !skip{print}' "$DOTFILES/CLAUDE.base.md"
} > "$DOTFILES/CLAUDE.md"

_local_instructions=()
if [[ -d "$DOTFILES/instructions/_local" ]]; then
    for f in "$DOTFILES/instructions/_local/"*.instructions.md; do
        [[ -f "$f" ]] || continue
        if head -20 "$f" | grep -qE '^auto-load:\s*false'; then
            continue
        fi
        _local_instructions+=("$f")
    done
fi
if [[ ${#_local_instructions[@]} -gt 0 ]]; then
    printf '\n## Local Instructions (auto-generated by bootstrap.sh)\n\n' >> "$DOTFILES/CLAUDE.md"
    for f in "${_local_instructions[@]}"; do
        _fname=$(basename "$f")
        printf '@~/dotfiles/instructions/_local/%s\n' "$_fname" >> "$DOTFILES/CLAUDE.md"
    done
fi

# Detect Windows (mirrors bootstrap.sh detect_os): file symlinks require admin
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) IS_WINDOWS=1 ;;
    *)                    IS_WINDOWS=0 ;;
esac

# Deploy to Claude consumer (mirrors bootstrap.sh: cp fallback on Windows)
if [[ "$IS_WINDOWS" == 1 ]]; then
    cp "$DOTFILES/CLAUDE.md" "$CLAUDE_DIR/CLAUDE.md"
else
    ln -sf "$DOTFILES/CLAUDE.md" "$CLAUDE_DIR/CLAUDE.md"
fi

# Deploy to Copilot consumer (mirrors bootstrap.sh copilot step)
if [[ "$IS_WINDOWS" == 1 ]]; then
    cp "$DOTFILES/CLAUDE.md" "$COPILOT_DIR/copilot-instructions.md"
else
    ln -sf "$DOTFILES/CLAUDE.md" "$COPILOT_DIR/copilot-instructions.md"
fi
SCRIPT
chmod +x "$FAKE_HOME/run-mirror.sh"

bash "$FAKE_HOME/run-mirror.sh" "$FAKE_HOME"

# ── Test 1: Generated CLAUDE.md exists ──────────────────────────────────────
if [[ -f "$FAKE_DOTFILES/CLAUDE.md" ]]; then
    _ok "CLAUDE.md is generated"
else
    _fail "CLAUDE.md is generated" "file not found"
fi

# ── Test 2: Claude consumer has identical content ───────────────────────────
# Accept either a symlink (Unix) or a byte-identical copy (Windows fallback).
if [[ -L "$FAKE_HOME/.claude/CLAUDE.md" ]] || [[ -f "$FAKE_HOME/.claude/CLAUDE.md" ]]; then
    CLAUDE_CONTENT=$(cat "$FAKE_HOME/.claude/CLAUDE.md")
    SOURCE_CONTENT=$(cat "$FAKE_DOTFILES/CLAUDE.md")
    if [[ "$CLAUDE_CONTENT" == "$SOURCE_CONTENT" ]]; then
        _ok "Claude consumer instructions match generated CLAUDE.md"
    else
        _fail "Claude consumer instructions match" "content differs"
    fi
else
    _fail "Claude consumer instructions" "~/.claude/CLAUDE.md is not a symlink or file"
fi

# ── Test 3: Copilot consumer has identical content ──────────────────────────
if [[ -L "$FAKE_HOME/.copilot/copilot-instructions.md" ]] || [[ -f "$FAKE_HOME/.copilot/copilot-instructions.md" ]]; then
    COPILOT_CONTENT=$(cat "$FAKE_HOME/.copilot/copilot-instructions.md")
    SOURCE_CONTENT=$(cat "$FAKE_DOTFILES/CLAUDE.md")
    if [[ "$COPILOT_CONTENT" == "$SOURCE_CONTENT" ]]; then
        _ok "Copilot consumer instructions match generated CLAUDE.md"
    else
        _fail "Copilot consumer instructions match" "content differs from CLAUDE.md"
    fi
else
    _fail "Copilot consumer instructions" "~/.copilot/copilot-instructions.md is not a symlink or file"
fi

# ── Test 4: Claude and Copilot point to the same source ─────────────────────
# On Unix both are symlinks to the same target. On Windows both are byte-identical
# copies of CLAUDE.md — verify content equality instead of readlink targets.
CLAUDE_TARGET=$(readlink "$FAKE_HOME/.claude/CLAUDE.md" 2>/dev/null || true)
COPILOT_TARGET=$(readlink "$FAKE_HOME/.copilot/copilot-instructions.md" 2>/dev/null || true)
if [[ -n "$CLAUDE_TARGET" && -n "$COPILOT_TARGET" && "$CLAUDE_TARGET" == "$COPILOT_TARGET" ]]; then
    _ok "Claude and Copilot symlinks resolve to the same file"
elif [[ -z "$CLAUDE_TARGET" && -z "$COPILOT_TARGET" ]]; then
    # Windows fallback: both are copies — verify identical content
    if cmp -s "$FAKE_HOME/.claude/CLAUDE.md" "$FAKE_HOME/.copilot/copilot-instructions.md"; then
        _ok "Claude and Copilot copies are byte-identical (Windows fallback)"
    else
        _fail "same source" "Claude and Copilot copies differ on Windows"
    fi
else
    _fail "same source" "Claude -> $CLAUDE_TARGET, Copilot -> $COPILOT_TARGET"
fi

# ── Test 5: Copilot is NOT separately generated (no divergent source) ───────
# The copilot file must be a symlink to CLAUDE.md (Unix) or a byte-identical
# copy of it (Windows fallback) — never an independently generated file.
if [[ -L "$FAKE_HOME/.copilot/copilot-instructions.md" ]]; then
    _target=$(readlink "$FAKE_HOME/.copilot/copilot-instructions.md")
    if [[ "$_target" == "$FAKE_DOTFILES/CLAUDE.md" ]]; then
        _ok "Copilot instructions are not separately generated (symlink to CLAUDE.md)"
    else
        _fail "Copilot not separately generated" "points to $_target instead of CLAUDE.md"
    fi
elif cmp -s "$FAKE_HOME/.copilot/copilot-instructions.md" "$FAKE_DOTFILES/CLAUDE.md"; then
    _ok "Copilot instructions are not separately generated (Windows fallback copy matches CLAUDE.md)"
else
    _fail "Copilot not separately generated" "is a regular file, not a symlink"
fi

# ── Test 6: Idempotency — running again produces identical output ───────────
FIRST_MD5=$(md5sum "$FAKE_DOTFILES/CLAUDE.md" 2>/dev/null | cut -d' ' -f1 || shasum "$FAKE_DOTFILES/CLAUDE.md" | cut -d' ' -f1)
bash "$FAKE_HOME/run-mirror.sh" "$FAKE_HOME"
SECOND_MD5=$(md5sum "$FAKE_DOTFILES/CLAUDE.md" 2>/dev/null | cut -d' ' -f1 || shasum "$FAKE_DOTFILES/CLAUDE.md" | cut -d' ' -f1)
if [[ "$FIRST_MD5" == "$SECOND_MD5" ]]; then
    _ok "Bootstrap is idempotent (second run produces identical CLAUDE.md)"
else
    _fail "idempotent" "CLAUDE.md changed between runs"
fi

# ── Test 7: Omitting copilot deploy would fail (structural check) ───────────
# Verify that bootstrap.sh still contains the copilot mirror logic
if grep -q 'ln -sf "$DOTFILES/CLAUDE.md" "$COPILOT_DIR/copilot-instructions.md"' "$REPO_ROOT/bin/bootstrap.sh"; then
    _ok "bootstrap.sh contains copilot symlink from CLAUDE.md"
elif grep -q 'cp "$DOTFILES/CLAUDE.md" "$COPILOT_DIR/copilot-instructions.md"' "$REPO_ROOT/bin/bootstrap.sh"; then
    _ok "bootstrap.sh contains copilot copy from CLAUDE.md"
else
    _fail "bootstrap.sh copilot mirror" "no ln/cp of CLAUDE.md to copilot-instructions.md found"
fi

# ── Test 8: Local instructions appear in mirrored content ───────────────────
if grep -q 'sample.instructions.md' "$FAKE_HOME/.copilot/copilot-instructions.md"; then
    _ok "Local instructions propagate to Copilot consumer"
else
    _fail "Local instructions in Copilot" "sample.instructions.md not found in copilot-instructions.md"
fi

echo
echo "════════════════════════════════════════════════"
printf "  \033[32m%d passed\033[0m  \033[31m%d failed\033[0m\n" "$PASS" "$FAIL"

if [[ ${#FAILURES[@]} -gt 0 ]]; then
    echo
    echo "  Failures:"
    for f in "${FAILURES[@]}"; do
        printf "    \033[31m✗\033[0m %s\n" "$f"
    done
    echo
    exit 1
fi

echo
exit 0
