import path from "node:path";
import { run, Output, StructuredOutputError, claudeCode } from "@ai-hero/sandcastle";
import { noSandbox } from "@ai-hero/sandcastle/sandboxes/no-sandbox";
import { ArchitectureReviewOutput } from "../schemas/architecture-review-output.js";
import { sh } from "../lib/shell-helpers.js";
import type { DispatchContext } from "../lib/types.js";

export async function runArchitectureReview(ctx: DispatchContext): Promise<void> {
  const { repoDir, model, promptsDir, args } = ctx;
  const issueNumber = args.issue as string | undefined;

  console.log(`[architecture-review] Starting architecture review...`);

  try {
    const result = await run({
      agent: claudeCode(model),
      sandbox: noSandbox(),
      cwd: repoDir,
      promptFile: path.join(promptsDir, "architecture-review.md"),
      promptArgs: {
        ...(issueNumber ? { ISSUE_NUMBER: issueNumber } : {}),
      },
      output: Output.object({ tag: "output", schema: ArchitectureReviewOutput }),
      logging: { type: "stdout" },
    });

    const { findings, prdSuggestions, summary } = result.output;

    console.log(`\n[architecture-review] Complete`);
    console.log(`  summary: ${summary.slice(0, 120)}...`);
    console.log(`  findings: ${findings.length}`);
    console.log(`  PRD suggestions: ${prdSuggestions.length}`);

    for (const finding of findings) {
      console.log(`  [${finding.severity}] ${finding.area}: ${finding.description.slice(0, 80)}`);
    }

    // Create PRD issues for any suggestions
    for (const suggestion of prdSuggestions) {
      const body = [
        `## ${suggestion.title}`,
        "",
        suggestion.description,
        "",
        "---",
        `_Generated by architecture review${issueNumber ? ` (from #${issueNumber})` : ""}._`,
      ].join("\n");

      const issueUrl = sh({
        cmd: "gh",
        args: ["issue", "create", "--title", suggestion.title, "--body-file", "-", "--label", "architecture"],
        cwd: repoDir,
        input: body,
      });
      console.log(`[architecture-review] Created issue: ${issueUrl}`);
    }
  } catch (error) {
    if (error instanceof StructuredOutputError) {
      console.error(`[architecture-review] Failed: malformed agent output`);
      console.error(`[architecture-review] Tag: <${error.tag}>`);
      console.error(`[architecture-review] Raw matched: ${error.rawMatched ?? "(no match found)"}`);
      if (error.cause) console.error(`[architecture-review] Cause:`, error.cause);
      process.exit(1);
    }
    throw error;
  }
}
